// <auto-generated />
using System;
using InvoiceManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvoiceManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InvoiceDbContext))]
    [Migration("20260716134713_UseIntegerAuditUserIds")]
    partial class UseIntegerAuditUserIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvoiceManagement.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("TenantId", "IsActive", "LegalName");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("InvoiceManagement.Domain.Customers.CustomerLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.Property<int>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("StateProvince")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id");

                    b.HasIndex("TenantId", "CustomerId", "Name")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("CustomerLocations", (string)null);
                });

            modelBuilder.Entity("InvoiceManagement.Domain.Invoices.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BillToAddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BillToAddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BillToCity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BillToCountryCode")
                        .HasColumnType("char(2)");

                    b.Property<string>("BillToCustomerCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BillToLegalName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BillToPostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BillToStateProvince")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BillToTaxNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date");

                    b.Property<int>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly?>("PaidDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("StatusId");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("TaxTotal")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Total")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTime>("ValidFromUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidFromUtc");

                    b.Property<DateTime>("ValidToUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidToUtc");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId", "InvoiceNumber")
                        .IsUnique()
                        .HasFilter("[InvoiceNumber] IS NOT NULL");

                    b.HasIndex("TenantId", "CustomerId", "CustomerLocationId");

                    b.HasIndex("TenantId", "IsActive", "CustomerId", "CreatedUtc")
                        .IsDescending(false, false, false, true);

                    b.HasIndex("TenantId", "IsActive", "Status", "DueDate");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("TenantId", "IsActive", "Status", "DueDate"), new[] { "CurrencyCode", "Total" });

                    b.HasIndex("TenantId", "IsActive", "Status", "CreatedUtc", "Id")
                        .IsDescending(false, false, false, true, true);

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("TenantId", "IsActive", "Status", "CreatedUtc", "Id"), new[] { "InvoiceNumber", "CustomerId", "Total", "CurrencyCode", "DueDate" });

                    b.ToTable("Invoices", null, t =>
                        {
                            t.HasCheckConstraint("CK_Invoices_Amounts", "[Subtotal] >= 0 AND [TaxTotal] >= 0 AND [Total] >= 0 AND [Total] = [Subtotal] + [TaxTotal]");

                            t.HasCheckConstraint("CK_Invoices_Dates", "[DueDate] IS NULL OR [IssueDate] IS NULL OR [DueDate] >= [IssueDate]");

                            t.HasCheckConstraint("CK_Invoices_Deactivation", "[IsActive] = 1 OR [StatusId] = 1");

                            t.HasCheckConstraint("CK_Invoices_Draft", "[StatusId] <> 1 OR ([InvoiceNumber] IS NULL AND [IssueDate] IS NULL AND [PaidDate] IS NULL)");

                            t.HasCheckConstraint("CK_Invoices_IssuedSnapshot", "[StatusId] NOT IN (2, 3) OR ([InvoiceNumber] IS NOT NULL AND [IssueDate] IS NOT NULL AND [DueDate] IS NOT NULL AND [BillToCustomerCode] IS NOT NULL AND [BillToLegalName] IS NOT NULL AND [BillToAddressLine1] IS NOT NULL AND [BillToCity] IS NOT NULL AND [BillToCountryCode] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Invoices_Paid", "([StatusId] = 3 AND [PaidDate] IS NOT NULL) OR ([StatusId] <> 3 AND [PaidDate] IS NULL)");

                            t.HasCheckConstraint("CK_Invoices_Void", "([StatusId] = 4 AND [VoidReason] IS NOT NULL) OR ([StatusId] <> 4 AND [VoidReason] IS NULL)");
                        });

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("InvoicesHistory", "history");
                                ttb
                                    .HasPeriodStart("ValidFromUtc")
                                    .HasColumnName("ValidFromUtc");
                                ttb
                                    .HasPeriodEnd("ValidToUtc")
                                    .HasColumnName("ValidToUtc");
                            }));
                });

            modelBuilder.Entity("InvoiceManagement.Domain.Invoices.InvoiceLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<short>("LineNumber")
                        .HasColumnType("smallint");

                    b.Property<int>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTime>("ValidFromUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidFromUtc");

                    b.Property<DateTime>("ValidToUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidToUtc");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id");

                    b.HasIndex("TenantId", "InvoiceId", "LineNumber")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("InvoiceLineItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_InvoiceLineItems_Amounts", "[NetAmount] >= 0 AND [TaxAmount] >= 0 AND [TotalAmount] = [NetAmount] + [TaxAmount]");

                            t.HasCheckConstraint("CK_InvoiceLineItems_Values", "[LineNumber] > 0 AND [Quantity] > 0 AND [UnitPrice] >= 0 AND [TaxRate] >= 0 AND [TaxRate] <= 1");
                        });

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("InvoiceLineItemsHistory", "history");
                                ttb
                                    .HasPeriodStart("ValidFromUtc")
                                    .HasColumnName("ValidFromUtc");
                                ttb
                                    .HasPeriodEnd("ValidToUtc")
                                    .HasColumnName("ValidToUtc");
                            }));
                });

            modelBuilder.Entity("InvoiceManagement.Domain.Invoices.InvoiceNumberSequence", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("FiscalYear")
                        .HasColumnType("smallint");

                    b.Property<long>("CurrentValue")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("TenantId", "FiscalYear");

                    b.ToTable("InvoiceNumberSequences", null, t =>
                        {
                            t.HasCheckConstraint("CK_InvoiceNumberSequences_Value", "[CurrentValue] >= 0");
                        });
                });

            modelBuilder.Entity("InvoiceManagement.Domain.Invoices.InvoiceStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChangedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("ChangedUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<byte?>("FromStatus")
                        .HasColumnType("tinyint")
                        .HasColumnName("FromStatusId");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("ToStatus")
                        .HasColumnType("tinyint")
                        .HasColumnName("ToStatusId");

                    b.HasKey("Id");

                    b.HasIndex("FromStatus");

                    b.HasIndex("ToStatus");

                    b.HasIndex("TenantId", "InvoiceId", "ChangedUtc")
                        .IsDescending(false, false, true);

                    b.ToTable("InvoiceStatusHistory", (string)null);
                });

            modelBuilder.Entity("InvoiceManagement.Domain.Invoices.InvoiceStatusReference", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("SortOrder")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("InvoiceStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Code = "Draft",
                            DisplayName = "Draft",
                            SortOrder = (byte)1
                        },
                        new
                        {
                            Id = (byte)2,
                            Code = "Issued",
                            DisplayName = "Issued",
                            SortOrder = (byte)2
                        },
                        new
                        {
                            Id = (byte)3,
                            Code = "Paid",
                            DisplayName = "Paid",
                            SortOrder = (byte)3
                        },
                        new
                        {
                            Id = (byte)4,
                            Code = "Void",
                            DisplayName = "Void",
                            SortOrder = (byte)4
                        });
                });

            modelBuilder.Entity("InvoiceManagement.Domain.Platform.IdempotencyRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<byte[]>("RequestHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("ResponseStatus")
                        .HasColumnType("smallint");

                    b.Property<byte>("State")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresUtc");

                    b.HasIndex("TenantId", "Operation", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("IdempotencyRequests", (string)null);
                });

            modelBuilder.Entity("InvoiceManagement.Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tenants", null, t =>
                        {
                            t.HasCheckConstraint("CK_Tenants_Name_NotBlank", "LEN(LTRIM(RTRIM([Name]))) > 0");

                            t.HasCheckConstraint("CK_Tenants_Slug_NotBlank", "LEN(LTRIM(RTRIM([Slug]))) > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedBy = 1,
                            CreatedUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ModifiedBy = 1,
                            Name = "Demo Tenant",
                            Slug = "demo"
                        });
                });

            modelBuilder.Entity("InvoiceManagement.Domain.Customers.Customer", b =>
                {
                    b.HasOne("InvoiceManagement.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("InvoiceManagement.Domain.Customers.CustomerLocation", b =>
                {
                    b.HasOne("InvoiceManagement.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CustomerId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("InvoiceManagement.Domain.Invoices.Invoice", b =>
                {
                    b.HasOne("InvoiceManagement.Domain.Invoices.InvoiceStatusReference", null)
                        .WithMany()
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("InvoiceManagement.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("InvoiceManagement.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CustomerId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("InvoiceManagement.Domain.Customers.CustomerLocation", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CustomerId", "CustomerLocationId")
                        .HasPrincipalKey("TenantId", "CustomerId", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("InvoiceManagement.Domain.Invoices.InvoiceLineItem", b =>
                {
                    b.HasOne("InvoiceManagement.Domain.Invoices.Invoice", null)
                        .WithMany("LineItems")
                        .HasForeignKey("TenantId", "InvoiceId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("InvoiceManagement.Domain.Invoices.InvoiceNumberSequence", b =>
                {
                    b.HasOne("InvoiceManagement.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("InvoiceManagement.Domain.Invoices.InvoiceStatusHistory", b =>
                {
                    b.HasOne("InvoiceManagement.Domain.Invoices.InvoiceStatusReference", null)
                        .WithMany()
                        .HasForeignKey("FromStatus")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("InvoiceManagement.Domain.Invoices.InvoiceStatusReference", null)
                        .WithMany()
                        .HasForeignKey("ToStatus")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("InvoiceManagement.Domain.Invoices.Invoice", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("TenantId", "InvoiceId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("InvoiceManagement.Domain.Platform.IdempotencyRequest", b =>
                {
                    b.HasOne("InvoiceManagement.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("InvoiceManagement.Domain.Invoices.Invoice", b =>
                {
                    b.Navigation("LineItems");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
